spring:
  application:
    name: itemService
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 176.135.2.10
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
---
server:
  port: 8081
spring:
  profiles: item1

---
server:
  port: 8091
spring:
  profiles: item2
      