spring:
  application:
    name: orderService
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 176.135.2.10
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true
 
management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 8094
